# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [ "--fix=lf" ]
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: check-yaml
        args: [ --allow-multiple-documents ]
        exclude: |
          (?x)^(
              .+/templates/.+\.ya?ml
          )$
      - id: check-json
      - id: check-ast
      - id: requirements-txt-fixer
      - id: name-tests-test
  - repo: https://github.com/editorconfig-checker/editorconfig-checker.python
    rev: 3.11.1
    hooks:
      - id: editorconfig-checker
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.38.0
    hooks:
      - id: check-github-workflows
      - id: check-jsonschema
        name: "Validate yamllint config"
        files: ^\.yamllint\.ya?ml$
        types: [ yaml ]
        args:
          - --schemafile
          - https://json.schemastore.org/yamllint.json
      - id: check-jsonschema
        name: "Validate markdownlint config"
        files: ^\.markdownlint\.ya?ml$
        types: [ yaml ]
        args:
          - --schemafile
          - https://raw.githubusercontent.com/DavidAnson/markdownlint/main/schema/markdownlint-config-schema.json
      - id: check-jsonschema
        name: "Validate Hadolint config"
        files: ^\.hadolint\.ya?ml$
        types: [ yaml ]
        args:
          - --schemafile
          - https://raw.githubusercontent.com/hadolint/hadolint/master/contrib/hadolint.json
      - id: check-jsonschema
        name: "Validate container-structure-test config"
        files: container-structure-test\.ya?ml$
        types: [ yaml ]
        args:
          - --schemafile
          - https://json.schemastore.org/container-structure-test.json
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.38.0
    hooks:
      - id: yamllint
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.49.1
    hooks:
      - id: markdownlint
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.16.7
    hooks:
      # fix imports
      - id: ruff-check
        name: ruff-check-imports
        args: [ "check", "--select", "I", "--fix" ]
      # fix other
      - id: ruff-check
        args: [ "--fix" ]
      # format
      - id: ruff-format
  - repo: https://github.com/hadolint/hadolint
    rev: v2.15.1
    hooks:
      - id: hadolint
  - repo: https://github.com/gruntwork-io/pre-commit
    rev: v0.1.30
    hooks:
      - id: helmlint
