# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

sonar.projectKey=balihb_devops-task
sonar.organization=balihb
#sonar.verbose=true
#sonar.log.level=DEBUG
sonar.qualitygate.wait=true
# renovate: datasource=docker depName=python
sonar.python.version=3.13
sonar.sourceEncoding=UTF-8
sonar.sources=src/,Dockerfile
sonar.tests=tests/
sonar.python.coverage.reportPaths=.report/coverage/coverage.xml
sonar.python.mypy.reportPaths=.report/mypy/output.txt
sonar.python.xunit.reportPath=.report/junit/*.xml
sonar.sarifReportPaths=.report/checkov/results_sarif.sarif
