# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

[tox]
min_version = 4.20
skip_missing_interpreters = false
envlist =
    clean
    # renovate: datasource=docker depName=python
    3.13
    mypy
    deptry

[testenv]
pass_env =
    CI_*
    DOCKER_*
    FORCE_COLOR
    GITHUB_*
    GIT_*
    NO_COLOR
    PIP_*
    PYTEST_*
    PYTHONUNBUFFERED
    PY_COLORS
    TERM
deps =
    -r requirements-test.txt
commands = pytest {posargs} \
    --cov=helloapp \
    --cov-append \
    --cov-report=term-missing \
    --cov-report xml:.report/coverage/coverage.xml \
    --cov-report html:.report/htmlcov \
    --junitxml=.report/junit/result.xml \
    --html=.report/html/report.html

[testenv:clean]
skip_install = true
pass_env =
    FORCE_COLOR
    NO_COLOR
    PIP_*
    PYTHONUNBUFFERED
    PY_COLORS
    TERM
deps =
    # renovate: datasource=pypi
    coverage==7.10.7
commands =
    coverage erase

[testenv:mypy]
skip_install = true
pass_env =
    FORCE_COLOR
    MYPY_*
    NO_COLOR
    PIP_*
    PYTHONUNBUFFERED
    PY_COLORS
    TERM
deps =
    -r requirements.txt
    -r requirements-test.txt
    # renovate: datasource=pypi
    mypy==1.17.1
    # renovate: datasource=pypi
    mypy[reports]==1.17.1
commands =
    python -c "import os, re, shlex, subprocess, sys; \
    from pathlib import Path; \
    result = subprocess.run(['mypy'] + shlex.split('{posargs:src tests}'), check=False, text=True, capture_output=True); \
    result.stdout.strip() and sys.stdout.write(result.stdout); \
    result.stderr.strip() and sys.stderr.write(result.stderr); \
    output = Path(os.getenv('MYPY_TOX_OUTPUT', default='.report/mypy/output.txt')); \
    output.parent.mkdir(parents=True, exist_ok=True); \
    output.write_text(re.compile(r'\x1b\\[[0-9;]*?m').sub('', result.stdout)); \
    sys.exit(1 if result.returncode == 2 else 0)"

[testenv:deptry]
skip_install = true
pass_env =
    FORCE_COLOR
    NO_COLOR
    PIP_*
    PYTHONUNBUFFERED
    PY_COLORS
    TERM
deps =
    -r requirements.txt
    # renovate: datasource=pypi
    deptry==0.23.1
commands =
    deptry src \
    --json-output .deptry-output.json
