# Licensed under the P-EADCA Universal Waiver License (PUWL v2.0draft02)
# See LICENSE.puwl in the project root for details.

name: Build

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*.*.*'
  release:
    types: [ released ]
  pull_request:
    paths:
      - '.dive-ci.yaml'
      - '.dockerignore'
      - '.github/workflows/build.yml'
      - 'Dockerfile'
      - 'charts'
      - 'container-structure-test.yaml'
      - 'docker-entrypoint.sh'
      - 'mise.docker.toml'
      - 'pyproject.toml'
      - 'requirements-build.txt'
      - 'requirements.txt'
      - 'src'
      - 'tests'
  workflow_dispatch:

env:
  # generic
  FORCE_COLOR: '1'
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PIP_PROGRESS_BAR: 'off'
  PYTHONUNBUFFERED: '1'
  PY_COLORS: '1'
  TERM: ansi

  # cache
  PIP_CACHE_DIR: ${{ github.workspace }}/.cache/pip
  XDG_CACHE_HOME: ${{ github.workspace }}/.cache/xdg
  npm_config_cache: ${{ github.workspace }}/.cache/npm

permissions: read-all

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: '0'

      - name: Cache tools
        uses: actions/cache@v4
        with:
          path: |
            ${{ env.PIP_CACHE_DIR }}
            ${{ env.XDG_CACHE_HOME }}
            ${{ env.npm_config_cache }}
          key: build-${{ hashFiles('.github/workflows/build.yml') }}

      - uses: jdx/mise-action@v3
        env:
          MISE_ENV: docker

      - name: Get version
        uses: ./.github/actions/get-version
        id: version

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1
        id: kind
        with:
          registry: true
          registry_enable_delete: true
          registry_image: registry:3
          registry_name: local-registry
          registry_port: 5001

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
          buildkitd-config-inline: |
            [registry."${{ steps.kind.outputs.LOCAL_REGISTRY }}"]
              http = true
              insecure = true
          driver-opts: network=host

      - name: Calculate lables
        run: |
          LOCAL_DOCKER_REPO="${{ steps.kind.outputs.LOCAL_REGISTRY }}/${{ github.repository }}"
          echo "LOCAL_DOCKER_REPO=${LOCAL_DOCKER_REPO}" >> $GITHUB_ENV
          echo "LOCAL_DOCKER_TAG=${LOCAL_DOCKER_REPO}:${{ steps.version.outputs.docker_version }}" >> $GITHUB_ENV
          echo "LOCAL_DOCKER_CACHE_TAG=${LOCAL_DOCKER_REPO}:cache" >> $GITHUB_ENV
          GHCR_DOCKER_REPO="ghcr.io/${{ github.repository }}"
          echo "GHCR_DOCKER_REPO=${GHCR_DOCKER_REPO}" >> $GITHUB_ENV
          echo "GHCR_DOCKER_TAG=${GHCR_DOCKER_REPO}:${{ steps.version.outputs.docker_version }}" >> $GITHUB_ENV
          echo "GHCR_DOCKER_LATEST_TAG=${GHCR_DOCKER_REPO}:latest" >> $GITHUB_ENV
          echo "GHCR_DOCKER_CACHE_TAG=${GHCR_DOCKER_REPO}:cache" >> $GITHUB_ENV

      - name: Build container image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64
          push: true
          load: true
          tags: |
            ${{ env.LOCAL_DOCKER_TAG }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.GHCR_DOCKER_CACHE_TAG }}
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.LOCAL_DOCKER_CACHE_TAG }}
          build-args: |
            APP_VERSION=${{ steps.version.outputs.version }}

      - name: Dive
        run: dive ${{ env.LOCAL_DOCKER_TAG }}
        env:
          CI: 'true'

      - name: Container Structure Tests
        run: container-structure-test test --image ${{ env.LOCAL_DOCKER_TAG }} --config container-structure-test.yaml

      - name: Update values.yaml
        uses: fjogeleit/yaml-update-action@main
        with:
          valueFile: 'charts/helloapp/Chart.yaml'
          propertyPath: 'appVersion'
          value: ${{ steps.version.outputs.docker_version }}
          commitChange: false

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (lint)
        env:
          VALIDATE_MAINTAINERS: 'false'
        run: ct lint --all --debug

      - name: Run chart-testing (install)
        run: ct install --all --print-config --helm-extra-set-args "--set=image.repository=${{ env.LOCAL_DOCKER_REPO }}"

      - name: Build container image
        uses: docker/build-push-action@v6
        if: github.event_name == 'release'
        with:
          platforms: linux/amd64
          push: true
          load: false
          tags: |
            ${{ env.GHCR_DOCKER_TAG }}
            ${{ env.GHCR_DOCKER_LATEST_TAG }}
          cache-from: |
            type=gha
            type=registry,ref=${{ env.GHCR_DOCKER_CACHE_TAG }}
          cache-to: |
            type=gha,mode=max
            type=registry,ref=${{ env.LOCAL_DOCKER_CACHE_TAG }}
            type=registry,ref=${{ env.GHCR_DOCKER_CACHE_TAG }}
          build-args: |
            APP_VERSION=${{ steps.version.outputs.version }}

      - name: Helm package
        if: github.event_name == 'release'
        run: |
          helm package ./charts/helloapp

      - name: Helm push
        if: github.event_name == 'release'
        run: |
          helm push helloapp-${{ steps.version.outputs.version }}.tgz oci://GHCR_DOCKER_REPO/helm-charts
